### ISSUE TITLE
Change 35c5b lowers precision by introducing additional aliases

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#1614]
This change: https://github.com/soot-oss/soot/commit/35c5bcb5e72401fcf5a064de5e1c9176b7c13da6 introduces new local variables which lowers our precision since many problems require alias analysis now. See reprod attached. Example:

```java
    public static String entryPoint() {
        ByteBuffer byteBuffer = null;
        try {
            byteBuffer = mySource();
            String hash = methodWithoutEffect(byteBuffer);
            return hash;
        } finally {
            mySink(byteBuffer);
        }
    }
```

The jimple for the above method used to look as follows:

```
     label1:
        r4 = staticinvoke <RequiresAlias: java.nio.ByteBuffer mySource()>();
        r0 = staticinvoke <RequiresAlias: java.lang.String methodWithoutEffect(java.nio.ByteBuffer)>(r4);
     label2:
        staticinvoke <RequiresAlias: void mySink(java.nio.ByteBuffer)>(r4);
        return r0;
     label3:
        $r2 := @caughtexception;
        staticinvoke <RequiresAlias: void mySink(java.nio.ByteBuffer)>(r4);
```

So it was easy to track the taint on `byteBuffer` by just following `r4`. With the latest changes, the body looks as follows:

```
     label1:
        $r0 = staticinvoke <RequiresAlias: java.nio.ByteBuffer mySource()>();
        r3 = $r0;
        $r1 = staticinvoke <RequiresAlias: java.lang.String methodWithoutEffect(java.nio.ByteBuffer)>($r0);
     label2:
        staticinvoke <RequiresAlias: void mySink(java.nio.ByteBuffer)>($r0);
        return $r1;
     label3:
        $r2 := @caughtexception;
        staticinvoke <RequiresAlias: void mySink(java.nio.ByteBuffer)>(r3);
```

which requires an alias analysis to understand that `$r0` and `r3` may be aliased in the catch block. This is a little tricky because there is an exceptional edge from `mySource` where they are not aliased yet, so we would need an alias analysis that does the right thing on control-flow merges at `label3`, but I don't see how this can be done in IFDS.

Is there a way to prevent the creation of this aliased variable?

See reprod attached. 

[reprod.zip](https://github.com/soot-oss/soot/files/6554940/reprod.zip)

**Comment by StevenArzt** [comment]
I see that there is an additional alias, but I don't see the problem for the data flow analysis. Semantically, we have two cases:

1) The call to ``mySource()`` (transitively) threw an exception. In that case, ``$r0`` is not yet initalized, and the alias doesn't matter.
2) The exception was thrown later. Two sub-cases:
2a) The assignment ``r3 = $r0`` threw some system-level error, e.g. ``OutOfMemoryError``. Extremely unlikely, and even if so, ``$r3`` would be unchanged.
2b) The exception was thrown later on, i.e., after processing ``r3 = $r0``. In that case, we have the alias.

The ``ExceptionalUnitGraph`` should model this just fine. Starting from the top, we taint ``$r0`` because of the source. There is an edge to the trap handler. The next line taints ``$r3``, yet another edge to the trap handler. We have set union as merge operator, so we have ``{$r0, r3}`` at the exception handler. That should be enough to detect the leak.

I'm pretty confident that FlowDroid (which is an IFDS-based data flow analysis) will find the link. If not, that's rather a bug than a limitation. In the end, I don't think the additional alias is much of a concern. Am I missing something?

**Comment by martinschaef** [comment]
Or let me put it differently: this alias (while, of course, semantically correct), would cost us some significant time. How much work would it be to remove that alias and go back to the way it was before?

**Comment by StevenArzt** [comment]
It depends on what you want to have. There is one path where ``mySink`` is called with a ``null`` argument and one path where it is called with tainted data. If you have an analysis that is not path-sensitive, you can either go with a may-style analysis (and report a leak) or go with a must-analysis (and report no leak). These two cases only differ in the merge operator in IFDS (set union or set intersection).

If we take the may analysis, we know that ``$r0`` and ``r3`` can potentially contain an open file at the beginning of the catch block (set union from all incoming edges). You're now facing a strong-update problem, i.e., the sink in fact kills taints and is more of a sanitizer than a sink. At all exit points of the method (your actual sinks), you check whether there is any taint left, and that's your non-closed files. At the sink, you must kill the taints on ``$r0`` and ``r3``. If that is your analysis design, I understand your problem.

Still, the semantics of the program are correct, as I analyzed above. Your task at hand would in fact require a path-sensitive must-alias analysis that restricts itself to _the same path that your IFDS analysis propagated along_. That doesn't work with IFDS in general (aside from just building a stack inside your taint abstraction which is totally inefficient).

Concerning the change: Are you able to identify the precise change in Soot that makes the code look different? What is the original Java bytecode? Was the previous Jimple code optimized by Soot by conincidence and that coincidence is now gone, or does the new version of Soot introduce the new variable?

Since March, we have worked heavily on type assignments. Soot now performs considerable code rewrites (including shadow variables) on import, since we had code that had no valid typing otherwise. The JVM and Dalvik use runtime typing, so you can get pretty nasty code. As far as I know, the shadow variables should only be introduced for constant initializers, though. Still, relying on a particular format of the Jimple code is always risky.

**Comment by martinschaef** [comment]
This is the change that introduced the issue:
https://github.com/soot-oss/soot/commit/35c5bcb5e72401fcf5a064de5e1c9176b7c13da6

Yes, I know that relying on the structure of the program is not the best idea, but the issue here is that some of our tests start breaking after that change and to make them pass we'd have to do a lot of engineering which we can't prioritize right now.

**Comment by StevenArzt** [comment]
That's exactly the type assigner fix that I mentioned. The core issue is described in the corresponding MR: https://github.com/soot-oss/soot/pull/1569.

Back then, we decided to over-approximate the splitting. In your case, the local (presumable ``$r0``) is initialized with ``null`` and only used for object-like references. A maximally-precise splitter would leave this local alone. However, identifying which shared initializations to split is tricky. I see two options here:

1) You can try to improve our splitter such that it avoids cases for which there is a valid typing without splitting. Keep in mind that type assignment runs after splitting, that makes it harder to find a good approximation of what to split.
2) Introduce an option to the ``jb`` phase to turn off the constant propagator and the shared initialization splitter. Your mileage may vary - if you're out of luck, you encounter code that fails type assignment and the Soot run fails entirely.

**Comment by martinschaef** [comment]
Cool. being able to turn off `jb.sils` would probably unblock us for now. Just to clarify: when you say

> if you're out of luck, you encounter code that fails type assignment and the Soot run fails entirely.

Does that mean Soot already failed on this code before this change, or may other parts of Soot fail now that implicitly depend on `jb.sils`?

**Comment by StevenArzt** [comment]
Soot failed on code before the change and we introduced ``jb.sils`` to fix the problem. Our change allows Soot to process code that it could not process before.

**Comment by martinschaef** [comment]
Ok, confirming that all my problems are gone if I can comment out this line:
https://github.com/soot-oss/soot/blob/3966f565db6dc2882c3538ffc39e44f4c14b5bcf/src/main/java/soot/JimpleBodyPack.java#L61

Could I get an option for that?

**Comment by linghuiluo** [comment]
try Options.v().setPhaseOption("jb.sils", "enabled:false");

**Comment by StevenArzt** [comment]
There should be an phase implicit option ``enabled`` for each phase:
   
All phases and subphases accept the option ``enabled``, which must be ``true`` for the phase or subphase to execute. To save you some typing, the pseudo-options ``on`` and ``off`` are equivalent to `enabled:true`` and ``enabled:false``, respectively. In addition, specifying any options for a phase  automatically enables that phase.

Thanks @linghuiluo for the precise syntax.

On the command-line we have

``
-p jb.sils enabled:false
```

**Comment by martinschaef** [comment]
Thanks @linghuiluo and @StevenArzt that seems to work.

Let me run a few more tests and I'll close the issue.

**Comment by ericbodden** [comment]
Hi all. Thanks for the helpful suggestions. I would have thought that another workaround could be to...
1. leave the new type assigner enabled, but...
2. after it has finished, before the analysis, apply an instance of soot.toolkits.scalar.LocalPacker to all bodies:
https://www.sable.mcgill.ca/soot/doc/soot/toolkits/scalar/LocalPacker.html
This _should_ get rid of the extra local.

@StevenArzt I did not understand why the extra local in Martin's case would be required or even useful. Both $r0 and r3 seem to be of type ByteBuffer, so why split them?

**Comment by ericbodden** [comment]
By the way Martin I think your core challenge is that for the typestate analysis you need a _must_-alias analysis, while for a taint analysis may-alias information is sufficient. And the control-flow edge from the source to the exception handler means that there _is_ no must-aliasing that any must-alias analysis could easily guarantee because there is a control-flow path along which the two variables may not alias. This might be addressable by making a must-alias analysis more clever but right now I think even Boomerang's must-alias analysis would not identify must-aliasing here.

**Comment by StevenArzt** [comment]
@ericbodden  The new transformer is not a new type assigner, but rather an additional step that runs _before_ the type assigner is invoked.  We want to ensure that the code is can be typed in the first place. The MR description has a few code examples why that is necessary, and why without the splitting, the type assigner may fail.

As I wrote, the splitter over-approximates the locals that need splitting. In Martin's case, the splitting is indeed unnecessary. Keep in mind that we don't have type information yet when the splitter runs. It gets untyped code that potentially doesn't even have a typing (that's why we split in the first place), and must make its decisions on that. We can't simply say "it's the same type", because we don't have types.

Precisely distinguishing cases that need splitting and ones that don't is far from easy, hence the over-approximation. Still, if someone has the time to look into the new splitter, I'm sure it can be improved.

Concerning the local packer, you can give it a try. I won't make any guesses on whether it can handle this case.

**Comment by martinschaef** [comment]
Thanks Eric! We actually try to stick to local may-alias analysis. What if we store the alias information in the IFDS fact but don't use them for the hash (to not mess with the summaries)? We may get different aliases on different paths but since we can't really override the merge, this would get hairy. Is there a way to reliably get the local may-alias set for a local?

**Comment by StevenArzt** [comment]
You can use SPARK's points-to sets for checking whether two locals alias:

``
Scene.v().getPointsToAnalysis().reachungObjects(myLocal)
```

That gives you a ``PointsToSet``. If you compute the ``PointsToSet`` of another local the same way, you can check for a non-empty intersection, i.e., a may-alias.

**Comment by martinschaef** [comment]
I'm only running CHA for now. Do I have to enable things for this to be computed?

**Comment by StevenArzt** [comment]
I'm not sure whether this works with CHA or only with SPARK. Give it a try, and we'll both be wiser ^^

**Comment by linghuiluo** [comment]
Just found some Explantation about Scene.v().getPointsToAnalysis() here https://github.com/soot-oss/soot/blob/3966f565db6dc2882c3538ffc39e44f4c14b5bcf/tutorial/guide/soot.tex

Current points-to set depends on the implementation used.
Soot provides three implementations of points-to analysis.Soot provides three implementations of the points-to interface: CHA (a dumb version), SPARK and Paddle.
 - The three implementations:The dumb version simply assumes that every variable might point to every other variable which is conservatively sound but not terribly accurate. Nevertheless the dumb points-to analysis may be of some value e.g. to create an imprecise call graph which may be used as starting point for e.g. a points-to analysis from which a more precise call graph might be constructed.

So I dont  think the method works for CHA.

**Comment by ericbodden** [comment]
@martinschaef 

> Is there a way to reliably get the local may-alias set for a local?

Did you look at https://soot-build.cs.uni-paderborn.de/public/origin/master/soot/soot-master/3.3.0/jdoc/soot/jimple/toolkits/pointer/LocalMayAliasAnalysis.html ?
This is a truly local analysis. And it is flow sensitive.

@StevenArzt Would it make sense to generally apply the LocalPacker after the TypeAssigner has completed, so that we get cleaner Jimple? Looking at [this line here](https://github.com/soot-oss/soot/blob/3966f565db6dc2882c3538ffc39e44f4c14b5bcf/src/main/java/soot/JimpleBodyPack.java#L87), should the LocalPacker not already run after the TypeAssigner anyway?

**Comment by StevenArzt** [comment]
@ericbodden Looks like it does indeed run. Probably the ``LocalPacker`` doesn't merge these locals, then. As I wrote above, I'm not so confident that the ``LocalPacker`` actually achieves a minimal set of locals in all cases. If someone wants to look into this, go ahead. In general, I'd rather err on the side of caution, though, and prefer a packer that leaves a few unnecessary locals here and there rather than break the Jimple code semantically in complex (side-)cases.

**Comment by ericbodden** [comment]
Sure, we should not merge what cannot be merged. Thanks!

**Comment by michael-emmi** [comment]
```
Options.v().setPhaseOption("jb", "use-original-names:true");
```

**Comment by michael-emmi** [comment]
Potentially related issue: local variables no longer seem to carry their original names. We had been using this option:
```
Options.v().setPhaseOption("jb", "use-original-names:true");
```
And seeing locals with names from the source program. However, the new code seems to interfere with this; now we just see many `$stack…` variables.

The original names appear again if we disable this pass as mentioned already:
```
Options.v().setPhaseOption("jb.sils", "enabled:false");
```
So just wondering: is this behavior of not preserving original names with sils intended? or is this a defect?

**Comment by linghuiluo** [comment]
Sounds like a defect to me

**Comment by martinschaef** [comment]
On more question on this. Maybe @linghuiluo or @StevenArzt know the answer:

In the example above, the IFDS has a transition from `r3 = $r0;` to `$r2 := @caughtexception;`. Of course, this is technically correct since any unit could throw, but in some cases, we would like to have a more optimistic throws analysis where simple assignments cannot throw. 

Is there a simple flag to influence that?

**Comment by martinschaef** [comment]
Fwiw, I tried `Options.v().set_omit_excepting_unit_edges(true);` but that doesn't seem to have an effect

**Comment by linghuiluo** [comment]
@martinschaef I don't think so. The ExceptionalUnitGraph takes Scene.v().getDefaultThrowAnalysis() which gives the UnitThrowAnalysis by default for Java bytecode.
