### ISSUE TITLE
Soot can't find class files due to package name

### ISSUE THREAD

**Issue by Danish-Nazir** [soot-oss/soot#1854]
<img width="1276" alt="Screenshot 2022-04-12 at 12 50 21 PM" src="https://user-images.githubusercontent.com/30548701/162909220-71cdcede-04c4-48ce-83ee-43fbaf95c5f7.png">

If I remove the package name and then compile code then soot works but if there is a package name then it can't find my classes. any reason why this is happening.

**Comment by jpstotz** [comment]
You are using the wrong `process-dir` argument. In Java you always use the root package directory when specifying a class path. Because you use the subdirectory `com/example` Soot uses the wrong package name. Use the root package directory ` ./soot-example` instead.

BTW: next time when posting command-line commands and output please just copy the text output to clipboard and paste it as text. Reading command output from screenshots with enforced line breaks is  a pain and not necessary.

**Comment by Danish-Nazir** [comment]
Thank you for replying. Yeah, it works now. Sorry for posting this eyesore of an image. I am looking at it and I agree I have a hard time reading code off the image. Next time I am posting codes instead of images of a code. Thanks for the feedback.
