### ISSUE TITLE
Is Soot 3.x still available through Maven?

### ISSUE THREAD

**Issue by amordahl** [soot-oss/soot#2090]
Hi,

I have a project that depends on Soot 3.0.0, from back when Soot was hosted at `https://soot-build.cs.uni-paderborn.de/`. Are these older versions of Soot still available anywhere? I can't find anything older than 4.1.0 on Maven Central. If not, is version 4.x of Soot backward compatible with 3.x?

Thanks!

Austin

**Comment by StevenArzt** [comment]
I would just give it a try with the current Soot version. I can't remember any huge interface changes, so your code should still compile unless you are doing some heavy integration into the internals of Soot.

**Comment by CalixBarrus** [comment]
I was able to get an old version of Soot from the VM associated with the amordahl/RethinkingAndroid_ISSTA2021 project, with the VM being hosted on this [zenodo artifact page](https://zenodo.org/records/4876728). In the VM, the soot JAR (v.3.2.0) was living in Maven's cache for installed JARs, along with a dozen or so other JARs that could be used to compile an old version of FlowDroid.

Feel free to close this issue.

**Comment by StevenArzt** [comment]
Thanks for letting us know. I'd rather not upload those older version to Maven Central, because this would require us to reconstruct the POM files across the entire chain of dependencies and upload that as well (Heros, Jasmin, etc.). If someone needs the old stuff, it's good to know where it can be found, though.
