### ISSUE TITLE
Instrumented Android app cannot launch/start

### ISSUE THREAD

**Issue by gazzaz86** [soot-oss/soot#667]
Hi everyone,
I was able to install the instrumented app on both emulator and real device, BUT it cannot start/launch. I got error message says that: "Unfortunately, MY_APPLICATION has stopped". 

I am trying to prove that the instrumentation has been successfully injected.
Any idea?!

**Comment by StevenArzt** [comment]
My first guess is that the instrumentation broke the app. Please try to run Soot on the app without your instrumentation, i.e., just read in the APK and write it back out without any changes. If the problem persists, we have an issue with Soot. Otherwise, you need to double-check your instrumentation code and see whether you have any bugs in there.

**Comment by pavanupb** [comment]
@gazzaz86 Please re-open the issue if this is still relevant.
