### ISSUE TITLE
Can't disable some basic analyses

### ISSUE THREAD

**Issue by florian-kuebler** [soot-oss/soot#671]
Whenever Soot produces Jimple, it is not possible to disable some basic analyses/optimizations (CopyPropagator, ConditionalBranchFolder, UnreachableCodeEliminator,  DeadAssignmentEliminator and UnusedLocalEliminator).
They are always applied in the PackManager in lines 981 to 985.

**Comment by StevenArzt** [comment]
This is by design. Depending on the source of the Jimple code, you might otherwise end up with broken code. In Dalvik, it is for instance totally fine to have type errors in unreachable portions of the code. If you don't run the UnreachableCodeEliminator, the type inference algorithm can only fail. Similar examples exist for other frontends and other optimizations.

**Comment by florian-kuebler** [comment]
This is a good argument for enabling them by default, but should you not be able to disable them?
In my case I've written a simple dead code analysis for evaluation purpose and can not test it (without removing the calls manually).
With my understanding of the PackManager and the soot phases the following should work:
There should be a phase/pack that includes the Analyses needed. In line 981 this pack should simply be applied. Then it should be possible to disable the analyses in the corresponding phase options. Isn't this right?

**Comment by pavanupb** [comment]
@florian-kuebler Please re-open the issue if this is still relevant.
